// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Account_Group")]
    public partial class AccountGroup
    {
        [Required]
        [StringLength(50)]
        public string AccountId { get; set; }
        public int GroupId { get; set; }
        [Key]
        public int Id { get; set; }

        [ForeignKey(nameof(AccountId))]
        [InverseProperty("AccountGroups")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(GroupId))]
        [InverseProperty("AccountGroups")]
        public virtual Group Group { get; set; }
    }
}