// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Account")]
    public partial class Account
    {
        public Account()
        {
            AccountGroups = new HashSet<AccountGroup>();
            Marks = new HashSet<Mark>();
            TeacherEvaluations = new HashSet<TeacherEvaluation>();
        }

        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(250)]
        public string Password { get; set; }
        [Required]
        [StringLength(50)]
        public string Fullname { get; set; }
        public int RoleId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Birthday { get; set; }
        [StringLength(11)]
        public string Phone { get; set; }
        [StringLength(150)]
        public string Address { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(10)]
        public string AccountCode { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty("Accounts")]
        public virtual Role Role { get; set; }
        [InverseProperty(nameof(AccountGroup.Account))]
        public virtual ICollection<AccountGroup> AccountGroups { get; set; }
        [InverseProperty(nameof(Mark.Account))]
        public virtual ICollection<Mark> Marks { get; set; }
        [InverseProperty(nameof(TeacherEvaluation.Teacher))]
        public virtual ICollection<TeacherEvaluation> TeacherEvaluations { get; set; }
    }
}