// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Account")]
    public partial class Account
    {
        public Account()
        {
            TeacherEvaluations = new HashSet<TeacherEvaluation>();
            Groups = new HashSet<Group>();
        }

        [Key]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(250)]
        public string Password { get; set; }
        [Required]
        [StringLength(50)]
        public string Fullname { get; set; }
        public int RoleId { get; set; }

        [ForeignKey(nameof(RoleId))]
        [InverseProperty("Accounts")]
        public virtual Role Role { get; set; }
        [InverseProperty(nameof(TeacherEvaluation.Teacher))]
        public virtual ICollection<TeacherEvaluation> TeacherEvaluations { get; set; }

        [ForeignKey("AccountId")]
        [InverseProperty(nameof(Group.Accounts))]
        public virtual ICollection<Group> Groups { get; set; }
    }
}