// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("CouncilEvaluation")]
    public partial class CouncilEvaluation
    {
        [Key]
        public int Id { get; set; }
        public int GroupId { get; set; }
        public double Point { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }

        [ForeignKey(nameof(GroupId))]
        [InverseProperty("CouncilEvaluations")]
        public virtual Group Group { get; set; }
    }
}