// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Group")]
    public partial class Group
    {
        public Group()
        {
            AccountGroups = new HashSet<AccountGroup>();
            Submits = new HashSet<Submit>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Semester { get; set; }
        public int Year { get; set; }
        public int ProjectId { get; set; }
        [StringLength(50)]
        public string GroupCode { get; set; }

        [ForeignKey(nameof(ProjectId))]
        [InverseProperty("Groups")]
        public virtual Project Project { get; set; }
        [InverseProperty(nameof(AccountGroup.Group))]
        public virtual ICollection<AccountGroup> AccountGroups { get; set; }
        [InverseProperty(nameof(Submit.Group))]
        public virtual ICollection<Submit> Submits { get; set; }
    }
}