// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Group")]
    public partial class Group
    {
        public Group()
        {
            CouncilEvaluations = new HashSet<CouncilEvaluation>();
            Accounts = new HashSet<Account>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Semester { get; set; }
        public int Year { get; set; }
        public int? ProjetId { get; set; }

        [ForeignKey(nameof(ProjetId))]
        [InverseProperty(nameof(Project.Groups))]
        public virtual Project Projet { get; set; }
        [InverseProperty(nameof(Models.CouncilEvaluation.Group))]
        public virtual ICollection<CouncilEvaluation> CouncilEvaluations { get; set; }

        [ForeignKey("GroupId")]
        [InverseProperty(nameof(Account.Groups))]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}