// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("MarkCategory")]
    public partial class MarkCategory
    {
        public MarkCategory()
        {
            Marks = new HashSet<Mark>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [StringLength(10)]
        public string Status { get; set; }

        [InverseProperty(nameof(Mark.Category))]
        public virtual ICollection<Mark> Marks { get; set; }
    }
}