// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Mark")]
    public partial class Mark
    {
        [Key]
        public int Id { get; set; }
        public double? Point { get; set; }
        public int CategoryId { get; set; }
        public int AccountId { get; set; }

        [ForeignKey(nameof(AccountId))]
        [InverseProperty("Marks")]
        public virtual Account Account { get; set; }
        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(MarkCategory.Marks))]
        public virtual MarkCategory Category { get; set; }
    }
}