// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Project")]
    public partial class Project
    {
        public Project()
        {
            Groups = new HashSet<Group>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string ProjectName { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }

        [InverseProperty(nameof(Group.Project))]
        public virtual ICollection<Group> Groups { get; set; }
    }
}