// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("Submit")]
    public partial class Submit
    {
        [Key]
        public int Id { get; set; }
        public int ReportId { get; set; }
        public int GroupId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime SubmitTime { get; set; }
        [Required]
        [StringLength(250)]
        public string ReportUrl { get; set; }
        [StringLength(250)]
        public string Comment { get; set; }

        [ForeignKey(nameof(GroupId))]
        [InverseProperty("Submits")]
        public virtual Group Group { get; set; }
        [ForeignKey(nameof(ReportId))]
        [InverseProperty("Submits")]
        public virtual Report Report { get; set; }
    }
}