// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Api.Models
{
    [Table("TeacherEvaluation")]
    public partial class TeacherEvaluation
    {
        [Key]
        public int Id { get; set; }
        public int SubmitId { get; set; }
        public int TeacherId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }
        public double Point { get; set; }
        [StringLength(250)]
        public string Description { get; set; }

        [ForeignKey(nameof(SubmitId))]
        [InverseProperty("TeacherEvaluations")]
        public virtual Submit Submit { get; set; }
        [ForeignKey(nameof(TeacherId))]
        [InverseProperty(nameof(Account.TeacherEvaluations))]
        public virtual Account Teacher { get; set; }
    }
}